theme = "catppuccin_frappe"

[editor]
cursorline = true
color-modes = true
bufferline = "multiple"
mouse = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = ["mode", "spacer", "version-control", "spacer", "separator", "file-base-name"]
center = ["diagnostics"]
right = ["selections", "position", "file-encoding", "file-type"]

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
esc = ["collapse_selection", "keep_primary_selection"]
