#!/bin/sh
PLATFORM=$(uname)

LS="/usr/bin/ls"

# The BSD version of ls doesn't handle colors the same way and doesn't seem
# to have any support for hyperlinks.
if [ ${PLATFORM} = "Darwin" ]; then
  LS="/usr/local/bin/gls"
fi

# If standard out is open, we're working interactively and want dircolors
if [ -t 1 ]; then
  if [ ${PLATFORM} = "Darwin" ]; then
    eval "$(gdircolors --bourne-shell ${XDG_CONFIG_HOME}/dircolors)"
  else
    eval "$(dircolors --bourne-shell ${XDG_CONFIG_HOME}/dircolors)"
  fi
fi 

exec $LS --color=auto --hyperlink=auto "$@"
